table Comments
	lineageTag: 363d2f51-5af0-46a9-b9ca-8a270554526e

	column 'Werk - Bezeichnung'
		dataType: string
		lineageTag: e9617c47-1919-40b2-b401-47d53af24f82
		summarizeBy: none
		sourceColumn: Werk - Bezeichnung

		annotation SummarizationSetBy = Automatic

	column Comment
		dataType: string
		lineageTag: 2285a32c-8cf9-4261-b66b-d26569657593
		summarizeBy: none
		sourceColumn: Comment

		annotation SummarizationSetBy = Automatic

	column Datum
		dataType: dateTime
		formatString: Long Date
		lineageTag: 276e9c38-f236-4022-b977-d302bb0b1b84
		summarizeBy: none
		sourceColumn: Datum

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Comments = m
		mode: import
		source =
				let
				    Quelle = SharePoint.Contents("https://cpgplc.sharepoint.com/sites/GroupControlling", [ApiVersion = 15]),
				    #"Shared Documents" = Quelle{[Name="Shared Documents"]}[Content],
				    #"Group Controlling" = #"Shared Documents"{[Name="Group Controlling"]}[Content],
				    #"Net New ITY" = #"Group Controlling"{[Name="Net New ITY"]}[Content],
				    #"06_Comments" = #"Net New ITY"{[Name="06_Comments"]}[Content],
				    #"Hinzugefügte benutzerdefinierte Spalte" = Table.AddColumn(#"06_Comments", "Datum", each Date.FromText(Text.Replace(Text.Start([Name], 10), "_", "-"))),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Hinzugefügte benutzerdefinierte Spalte",{{"Datum", type date}}),
				    #"Entfernte Spalten" = Table.RemoveColumns(#"Geänderter Typ",{"Name", "Extension", "Date accessed", "Date modified", "Date created", "Attributes", "Folder Path"}),
				    #"Gefilterte ausgeblendete Dateien1" = Table.SelectRows(#"Entfernte Spalten", each [Attributes]?[Hidden]? <> true),
				    #"Benutzerdefinierte Funktion aufrufen1" = Table.AddColumn(#"Gefilterte ausgeblendete Dateien1", "Datei transformieren", each #"Datei transformieren"([Content])),
				    #"Entfernte Spalten3" = Table.RemoveColumns(#"Benutzerdefinierte Funktion aufrufen1",{"Content"}),
				    #"Neu angeordnete Spalten" = Table.ReorderColumns(#"Entfernte Spalten3",{"Datei transformieren", "Datum"}),
				    #"Erweiterte Tabellenspalte1" = Table.ExpandTableColumn(#"Neu angeordnete Spalten", "Datei transformieren", Table.ColumnNames(#"Datei transformieren"(Beispieldatei))),
				    #"Entfernte Duplikate" = Table.Distinct(#"Erweiterte Tabellenspalte1")
				in
				    #"Entfernte Duplikate"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

