/// Berichtsjahr-Dimension (Reporting Year). Ein Berichtsjahr = das
/// Geschäftsjahr, das berichtet wird, inklusive seiner Vorjahres-Vergleichs-
/// basis. Ermöglicht FY26 und FY27 gleichzeitig im selben Modell.
/// Abgeleitet aus Szenario_Konfig[Berichtsjahr_Start]; Beziehung zu
/// Revenues[Berichtsjahr]. Ohne Slicer-Auswahl bleiben die bestehenden
/// (FY26-)Measures unverändert, da deren Szenarien nur FY26-Zeilen enthalten.
table DIM_Berichtsjahr
	lineageTag: 2761afdb-53cf-4ba0-b5f4-99198e071621

	column Berichtsjahr
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: 485021f8-3fad-4118-bb55-1ea6291e0b11
		summarizeBy: none
		sourceColumn: Berichtsjahr

		annotation SummarizationSetBy = User

	column Berichtsjahr_Label
		dataType: string
		lineageTag: d8c2dd96-3d9a-43b0-831b-601ecd88b526
		summarizeBy: none
		sourceColumn: Berichtsjahr_Label
		sortByColumn: Berichtsjahr

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition DIM_Berichtsjahr = m
		mode: import
		source = ```
				let
				    Jahre = Table.Distinct(Table.SelectColumns(Szenario_Konfig, {"Berichtsjahr_Start"})),
				    Umbenannt = Table.RenameColumns(Jahre, {{"Berichtsjahr_Start", "Berichtsjahr"}}),
				    Typisiert = Table.TransformColumnTypes(Umbenannt, {{"Berichtsjahr", Int64.Type}}),
				    MitLabel = Table.AddColumn(Typisiert, "Berichtsjahr_Label", each "FY" & Text.PadStart(Text.From(Number.Mod([Berichtsjahr] + 1, 100)), 2, "0"), type text)
				in
				    MitLabel
				```

	annotation PBI_ResultType = Table
