/// Szenario-Dimension (Actuals, Budget, Forecast-Runden). Wird aus
/// Szenario_Konfig abgeleitet – neue Forecast-Runden erscheinen hier
/// automatisch und stehen als Slicer zur Verfügung.
table DIM_Szenario
	lineageTag: 339b1122-9f4d-487b-afa9-0b52fd6c65f7

	column Szenario
		dataType: string
		lineageTag: 2c4164ca-21f1-4d29-ab4d-87926b3cd1c5
		summarizeBy: none
		sourceColumn: Szenario
		sortByColumn: Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: c7e1be0f-0107-49a6-aec5-305ed0b22eb4
		summarizeBy: none
		sourceColumn: Sort

		annotation SummarizationSetBy = User

	column Beschreibung
		dataType: string
		lineageTag: 3e1cf919-5328-49d7-92e4-7f3aaf2d45fb
		summarizeBy: none
		sourceColumn: Beschreibung

		annotation SummarizationSetBy = Automatic

	/// Anzeigename der Forecast-Runde (nur für die Vergleichsleiter gefüllt:
	/// Budget / 2+10 / 5+7 / 8+4 / 10+2 / Actual). Interne Szenarien (RF, FC02,
	/// ARO_RGF, R01) bleiben leer und werden in der Vergleichsansicht per
	/// Filter "Runde ist nicht leer" ausgeblendet.
	column Runde
		dataType: string
		lineageTag: 180c9ffb-fdf8-4abb-97c0-80deb70a0282
		summarizeBy: none
		sourceColumn: Runde
		sortByColumn: RundeSort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column RundeSort
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: f9a88fd8-1b15-498a-b36e-d3340270bd3f
		summarizeBy: none
		sourceColumn: RundeSort

		annotation SummarizationSetBy = User

	partition DIM_Szenario = m
		mode: import
		source = ```
				let
				    Beschreibungen = [
				        ACT     = "Actuals (Ist)",
				        BUD     = "Budget (eingefroren zum Budget-Snapshot)",
				        RGF     = "Rolling Forecast = aktueller FC 8+4 (Plan_RGF + R12) + Ist Vorjahr",
				        FC57    = "Forecast 5+7 (Plan_RGF ohne R12-Aufsatz) + Ist Vorjahr",
				        RF      = "Forecast RF/RTD + Ist Vorjahr",
				        P35     = "Plan 35/RTD + Ist Vorjahr",
				        R03     = "Forecast-Runde R03 (Snapshot)",
				        FC02    = "Forecast Plan 02 + Ist Vorjahr",
				        ARO_RGF = "ARO-Sicht auf RGF-Snapshot",
				        R01     = "Plan 01 (Recherche)",
				        BUD_FY27 = "Budget FY27 (Plan_20 FY27, Vorjahr = RGF+R12 FY26, CoC eingefroren zum FY27-Snapshot)"
				    ],
				    // Vergleichsleiter: Szenario-Kürzel -> Anzeigename + Sortierung.
				    // Zuordnung laut Version-Mapping des Controllings:
				    //   2+10 = Plan_R03 (R03), 5+7 = Plan_RGF ohne R12 (FC57),
				    //   8+4 = Plan_RGF + R12 (RGF), 10+2 = Plan_35 + RTD (P35).
				    RundeMap     = [ BUD = "Budget", R03 = "2+10", FC57 = "5+7", RGF = "8+4", P35 = "10+2", ACT = "Actual", BUD_FY27 = "Budget FY27" ],
				    RundeSortMap = [ BUD = 1,        R03 = 2,      FC57 = 3,     RGF = 4,     P35 = 5,      ACT = 6,      BUD_FY27 = 7 ],
				    Auswahl = Table.Distinct(Table.SelectColumns(Szenario_Konfig, {"Szenario", "Sort"})),
				    MitBeschreibung = Table.AddColumn(Auswahl, "Beschreibung", each Record.FieldOrDefault(Beschreibungen, [Szenario], [Szenario]), type text),
				    MitRunde = Table.AddColumn(MitBeschreibung, "Runde", each Record.FieldOrDefault(RundeMap, [Szenario], null), type nullable text),
				    MitRundeSort = Table.AddColumn(MitRunde, "RundeSort", each Record.FieldOrDefault(RundeSortMap, [Szenario], 99), Int64.Type)
				in
				    MitRundeSort
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
