table DIM_DATE
	lineageTag: c9978af4-b0e0-449a-87be-5ce8065fa95f
	dataCategory: Time

	column Datum
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: de41bc51-bc70-4873-8270-0513005c43c5
		summarizeBy: none
		sourceColumn: Datum

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Jahr
		dataType: int64
		formatString: 0
		lineageTag: a4e60fd5-42eb-4f80-94d1-689e04bb6bcc
		summarizeBy: sum
		sourceColumn: Jahr

		annotation SummarizationSetBy = Automatic

	column Monat
		dataType: string
		lineageTag: 6b40006e-945d-4256-ab57-aea0e2d677b5
		summarizeBy: none
		sourceColumn: Monat

		annotation SummarizationSetBy = Automatic

	column 'Monat Nummer'
		dataType: int64
		formatString: 0
		lineageTag: 60ac040d-d628-4851-9e3d-27c81d60a2ae
		summarizeBy: sum
		sourceColumn: Monat Nummer

		annotation SummarizationSetBy = Automatic

	column Tag
		dataType: int64
		formatString: 0
		lineageTag: 2a8cbba4-4d0c-49b5-84cf-ab5ca7fcb1c9
		summarizeBy: sum
		sourceColumn: Tag

		annotation SummarizationSetBy = Automatic

	column Wochentag
		dataType: string
		lineageTag: 9d065dd6-a2da-4df3-b751-c8165afccfd6
		summarizeBy: none
		sourceColumn: Wochentag

		annotation SummarizationSetBy = Automatic

	column 'Wochentag Nummer'
		dataType: int64
		formatString: 0
		lineageTag: bbad43c2-e1a1-4783-9667-321587d3c490
		summarizeBy: sum
		sourceColumn: Wochentag Nummer

		annotation SummarizationSetBy = Automatic

	column Quartal
		dataType: string
		lineageTag: 229ca829-b674-4a77-b9d5-e8bc7f9dfd0a
		summarizeBy: none
		sourceColumn: Quartal

		annotation SummarizationSetBy = Automatic

	column Halbjahr
		dataType: string
		lineageTag: a7afd489-3833-4848-b678-8782b4e12af7
		summarizeBy: none
		sourceColumn: Halbjahr

		annotation SummarizationSetBy = Automatic

	column FY_Jahr
		dataType: string
		lineageTag: 2a72f005-4101-40b3-b974-8ec3b76fcc95
		summarizeBy: none
		sourceColumn: FY_Jahr

		annotation SummarizationSetBy = Automatic

	column FY_JahrMonat
		dataType: string
		lineageTag: 1a2032d8-d3f8-46a0-b40a-17b1c386b159
		summarizeBy: none
		sourceColumn: FY_JahrMonat

		annotation SummarizationSetBy = Automatic

	column FY_Quartal
		dataType: string
		lineageTag: 31bd3901-93a2-4757-9f1d-30daf6fdd796
		summarizeBy: none
		sourceColumn: FY_Quartal
		sortByColumn: FY_QuartalNr

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column FY_QuartalNr
		dataType: int64
		formatString: 0
		lineageTag: 2719e0a1-696c-4ffe-ba75-c57bb96637b8
		summarizeBy: sum
		sourceColumn: FY_QuartalNr

		annotation SummarizationSetBy = Automatic

	column FY_Monat
		dataType: string
		lineageTag: ff5afd23-5088-451a-8504-fd5bd6a5db40
		summarizeBy: none
		sourceColumn: FY_Monat
		sortByColumn: FY_MonatNr

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column FY_MonatNr
		dataType: int64
		formatString: 0
		lineageTag: a6b234ab-d2f1-47cd-a901-a1ac0cd65e4d
		summarizeBy: sum
		sourceColumn: FY_MonatNr

		annotation SummarizationSetBy = Automatic

	column FY_Periode
		dataType: string
		lineageTag: fdf468ee-0f83-4cc7-8438-89bd06cdd387
		summarizeBy: none
		sourceColumn: FY_Periode
		sortByColumn: FY_MonatNr

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column FY_JahrLang
		dataType: string
		lineageTag: c1f6e982-0d98-435b-8279-6e2d287d2ee7
		summarizeBy: none
		sourceColumn: FY_JahrLang

		annotation SummarizationSetBy = Automatic

	partition DIM_DATE = m
		mode: import
		source = ```
				let
				    // === Parameter (einfach anpassen) ===
				    Startdatum = #date(2020, 1, 1),
				    Enddatum   = #date(2030, 12, 31),
				
				    // === Basis-Datumstabelle ===
				    DatumsListe   = List.Dates(Startdatum, Duration.Days(Enddatum - Startdatum) + 1, #duration(1,0,0,0)),
				    DatumsTabelle = Table.FromList(DatumsListe, Splitter.SplitByNothing(), {"Datum"}),
				
				    // === Kalender-Spalten ===
				    MitJahr        = Table.AddColumn(DatumsTabelle, "Jahr",           each Date.Year([Datum]),           Int64.Type),
				    MitMonatName   = Table.AddColumn(MitJahr,       "Monat",           each Date.MonthName([Datum]),      type text),
				    MitMonatNr     = Table.AddColumn(MitMonatName,  "Monat Nummer",    each Date.Month([Datum]),          Int64.Type),
				    MitTag         = Table.AddColumn(MitMonatNr,    "Tag",             each Date.Day([Datum]),            Int64.Type),
				    MitWochentag   = Table.AddColumn(MitTag,        "Wochentag",       each Date.DayOfWeekName([Datum]),  type text),
				    MitWochentagNr = Table.AddColumn(MitWochentag,  "Wochentag Nummer",each Date.DayOfWeek([Datum], Day.Monday) + 1, Int64.Type), // 1=Montag
				    MitQuartal     = Table.AddColumn(MitWochentagNr,"Quartal",         each "Q" & Text.From(Date.QuarterOfYear([Datum])), type text),
				    MitHalbjahr    = Table.AddColumn(MitQuartal,    "Halbjahr",        each if Date.Month([Datum]) <= 6 then "H1" else "H2", type text),
				
				    // === Fiscal Year ab 1. Oktober (FY2025/26-Format) – FEHLERFREI ===
				    AddFiscalColumns = Table.AddColumn(MitHalbjahr, "FiscalTemp", each 
				        let
				            m  = Date.Month([Datum]),
				            y  = Date.Year([Datum]),
				            
				            // FY-Startjahr und Endjahr
				            FY_Start = if m >= 10 then y else y - 1,
				            FY_End   = FY_Start + 1,
				            
				            // Fiscal Monat 1–12 (Okt=1, Nov=2, ..., Sep=12)
				            FY_Monat_Nr = if m >= 10 then m - 9 else m + 3,
				            
				            // Fiscal Quartal 1–4
				            FY_Quartal_Nr = Number.RoundUp(FY_Monat_Nr / 3)
				        in
				            [ 
				                FY_Jahr       = "FY" & Text.From(FY_Start) & "/" & Text.End(Text.From(FY_End), 2),   // FY2025/26
				                FY_JahrLang   = Text.From(FY_Start) & "/" & Text.From(FY_End),                     // 2025/26
				                FY_Quartal    = "FQ" & Text.From(FY_Quartal_Nr),                                   // FQ1 … FQ4
				                FY_Monat      = "FM" & Text.PadStart(Text.From(FY_Monat_Nr), 2, "0"),              // FM01 … FM12
				                FY_Periode    = "P" & Text.PadStart(Text.From(FY_Monat_Nr), 2, "0"),              // FP01 … FP12
				                FY_JahrMonat  = Text.From(FY_Start) & "-" & Text.PadStart(Text.From(FY_Monat_Nr), 2, "0"), // 2025-01 für Okt 2024
				                FY_MonatNr    = FY_Monat_Nr,                                                       // 1–12 als Zahl
				                FY_QuartalNr  = FY_Quartal_Nr                                                      // 1–4 als Zahl
				            ]
				    ),
				
				    // Record-Spalten aufklappen
				    Erweitert = Table.ExpandRecordColumn(AddFiscalColumns, "FiscalTemp", 
				        {"FY_Jahr", "FY_JahrLang", "FY_Quartal", "FY_Monat", "FY_Periode", "FY_JahrMonat", "FY_MonatNr", "FY_QuartalNr"}),
				
				    // Datentypen final setzen
				    #"Typen korrigiert" = Table.TransformColumnTypes(Erweitert,{
				        {"Datum", type date},
				        {"Jahr", Int64.Type},
				        {"Monat Nummer", Int64.Type},
				        {"Tag", Int64.Type},
				        {"Wochentag Nummer", Int64.Type},
				        {"FY_MonatNr", Int64.Type},
				        {"FY_QuartalNr", Int64.Type}
				    }),
				
				    // Spalten in gewünschter Reihenfolge
				    Ergebnis = Table.SelectColumns(#"Typen korrigiert", {
				        "Datum", "Jahr", "Monat Nummer", "Monat", "Tag",
				        "Wochentag", "Wochentag Nummer", "Quartal", "Halbjahr",
				        "FY_Jahr", "FY_JahrLang", "FY_JahrMonat",
				        "FY_Quartal", "FY_QuartalNr", "FY_Monat", "FY_MonatNr", "FY_Periode"
				    })
				
				in
				    Ergebnis
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

