/// Zentrale Datumstabelle. Geschäftsjahreslogik vollständig aus dem Parameter
/// "Geschäftsjahresbeginn" abgeleitet (FY_Startmonat) und damit für beliebig
/// viele Geschäftsjahre gültig. FY_Offset = Geschäftsjahr relativ zum
/// laufenden GJ (0 = aktuell, -1 = Vorjahr, ...).
table DIM_DATE
	lineageTag: c9978af4-b0e0-449a-87be-5ce8065fa95f
	dataCategory: Time

	column Datum
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: de41bc51-bc70-4873-8270-0513005c43c5
		summarizeBy: none
		sourceColumn: Datum

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Jahr
		dataType: int64
		formatString: 0
		lineageTag: a4e60fd5-42eb-4f80-94d1-689e04bb6bcc
		summarizeBy: none
		sourceColumn: Jahr

		annotation SummarizationSetBy = User

	column Monat
		dataType: string
		lineageTag: 6b40006e-945d-4256-ab57-aea0e2d677b5
		summarizeBy: none
		sourceColumn: Monat
		sortByColumn: 'Monat Nummer'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Monat Nummer'
		dataType: int64
		formatString: 0
		lineageTag: 60ac040d-d628-4851-9e3d-27c81d60a2ae
		summarizeBy: none
		sourceColumn: Monat Nummer

		annotation SummarizationSetBy = User

	column Tag
		dataType: int64
		formatString: 0
		lineageTag: 2a8cbba4-4d0c-49b5-84cf-ab5ca7fcb1c9
		summarizeBy: none
		sourceColumn: Tag

		annotation SummarizationSetBy = User

	column Wochentag
		dataType: string
		lineageTag: 9d065dd6-a2da-4df3-b751-c8165afccfd6
		summarizeBy: none
		sourceColumn: Wochentag
		sortByColumn: 'Wochentag Nummer'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Wochentag Nummer'
		dataType: int64
		formatString: 0
		lineageTag: bbad43c2-e1a1-4783-9667-321587d3c490
		summarizeBy: none
		sourceColumn: Wochentag Nummer

		annotation SummarizationSetBy = User

	column Quartal
		dataType: string
		lineageTag: 229ca829-b674-4a77-b9d5-e8bc7f9dfd0a
		summarizeBy: none
		sourceColumn: Quartal

		annotation SummarizationSetBy = Automatic

	column Halbjahr
		dataType: string
		lineageTag: a7afd489-3833-4848-b678-8782b4e12af7
		summarizeBy: none
		sourceColumn: Halbjahr

		annotation SummarizationSetBy = Automatic

	column FY_Jahr
		dataType: string
		lineageTag: 2a72f005-4101-40b3-b974-8ec3b76fcc95
		summarizeBy: none
		sourceColumn: FY_Jahr
		sortByColumn: FY_Start

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column FY_JahrMonat
		dataType: string
		lineageTag: 1a2032d8-d3f8-46a0-b40a-17b1c386b159
		summarizeBy: none
		sourceColumn: FY_JahrMonat

		annotation SummarizationSetBy = Automatic

	column FY_Quartal
		dataType: string
		lineageTag: 31bd3901-93a2-4757-9f1d-30daf6fdd796
		summarizeBy: none
		sourceColumn: FY_Quartal
		sortByColumn: FY_QuartalNr

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column FY_QuartalNr
		dataType: int64
		formatString: 0
		lineageTag: 2719e0a1-696c-4ffe-ba75-c57bb96637b8
		summarizeBy: none
		sourceColumn: FY_QuartalNr

		annotation SummarizationSetBy = User

	column FY_Monat
		dataType: string
		lineageTag: ff5afd23-5088-451a-8504-fd5bd6a5db40
		summarizeBy: none
		sourceColumn: FY_Monat
		sortByColumn: FY_MonatNr

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column FY_MonatNr
		dataType: int64
		formatString: 0
		lineageTag: a6b234ab-d2f1-47cd-a901-a1ac0cd65e4d
		summarizeBy: none
		sourceColumn: FY_MonatNr

		annotation SummarizationSetBy = User

	column FY_Periode
		dataType: string
		lineageTag: fdf468ee-0f83-4cc7-8438-89bd06cdd387
		summarizeBy: none
		sourceColumn: FY_Periode
		sortByColumn: FY_MonatNr

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column FY_JahrLang
		dataType: string
		lineageTag: c1f6e982-0d98-435b-8279-6e2d287d2ee7
		summarizeBy: none
		sourceColumn: FY_JahrLang
		sortByColumn: FY_Start

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	/// Kalenderjahr, in dem das Geschäftsjahr beginnt (z. B. 2025 für FY2025/26).
	column FY_Start
		dataType: int64
		formatString: 0
		lineageTag: e705b0e9-d8f0-42b0-ada1-a05d9bb656f5
		summarizeBy: none
		sourceColumn: FY_Start

		annotation SummarizationSetBy = User

	/// Geschäftsjahr relativ zum laufenden GJ: 0 = aktuell, -1 = Vorjahr, ...
	column FY_Offset
		dataType: int64
		formatString: 0
		lineageTag: e90c7d99-5d8d-494a-b91d-5ca889434574
		summarizeBy: none
		sourceColumn: FY_Offset

		annotation SummarizationSetBy = User

	partition DIM_DATE = m
		mode: import
		source = ```
				let
				    // Kalenderbereich rollierend um den konfigurierten GJ-Beginn
				    Startdatum = Date.StartOfYear(Date.AddYears(Geschäftsjahresbeginn, -6)),
				    Enddatum = Date.EndOfYear(Date.AddYears(Geschäftsjahresbeginn, 3)),

				    DatumsListe = List.Dates(Startdatum, Duration.Days(Enddatum - Startdatum) + 1, #duration(1, 0, 0, 0)),
				    DatumsTabelle = Table.FromList(DatumsListe, Splitter.SplitByNothing(), {"Datum"}),

				    // Kalender-Spalten
				    MitJahr        = Table.AddColumn(DatumsTabelle, "Jahr",             each Date.Year([Datum]),          Int64.Type),
				    MitMonatName   = Table.AddColumn(MitJahr,       "Monat",            each Date.MonthName([Datum]),     type text),
				    MitMonatNr     = Table.AddColumn(MitMonatName,  "Monat Nummer",     each Date.Month([Datum]),         Int64.Type),
				    MitTag         = Table.AddColumn(MitMonatNr,    "Tag",              each Date.Day([Datum]),           Int64.Type),
				    MitWochentag   = Table.AddColumn(MitTag,        "Wochentag",        each Date.DayOfWeekName([Datum]), type text),
				    MitWochentagNr = Table.AddColumn(MitWochentag,  "Wochentag Nummer", each Date.DayOfWeek([Datum], Day.Monday) + 1, Int64.Type),
				    MitQuartal     = Table.AddColumn(MitWochentagNr, "Quartal",         each "Q" & Text.From(Date.QuarterOfYear([Datum])), type text),
				    MitHalbjahr    = Table.AddColumn(MitQuartal,    "Halbjahr",         each if Date.Month([Datum]) <= 6 then "H1" else "H2", type text),

				    // Geschäftsjahres-Spalten – abgeleitet aus FY_Startmonat,
				    // dadurch gültig für beliebig viele Geschäftsjahre
				    MitFiscal = Table.AddColumn(MitHalbjahr, "FiscalTemp", each
				        let
				            FY_Start = fnFiscal_DatumZuGJ([Datum]),
				            FY_Ende = FY_Start + 1,
				            FY_Monat_Nr = fnFiscal_DatumZuPeriode([Datum]),
				            FY_Quartal_Nr = Number.RoundUp(FY_Monat_Nr / 3)
				        in
				            [
				                FY_Start      = FY_Start,
				                FY_Offset     = FY_Start - Aktuelles_Geschäftsjahr,
				                FY_Jahr       = "FY" & Text.From(FY_Start) & "/" & Text.End(Text.From(FY_Ende), 2),
				                FY_JahrLang   = Text.From(FY_Start) & "/" & Text.End(Text.From(FY_Ende), 2),
				                FY_Quartal    = "FQ" & Text.From(FY_Quartal_Nr),
				                FY_Monat      = "FM" & Text.PadStart(Text.From(FY_Monat_Nr), 2, "0"),
				                FY_Periode    = "P" & Text.PadStart(Text.From(FY_Monat_Nr), 2, "0"),
				                FY_JahrMonat  = Text.From(FY_Start) & "-" & Text.PadStart(Text.From(FY_Monat_Nr), 2, "0"),
				                FY_MonatNr    = FY_Monat_Nr,
				                FY_QuartalNr  = FY_Quartal_Nr
				            ]
				    ),
				    Erweitert = Table.ExpandRecordColumn(MitFiscal, "FiscalTemp",
				        {"FY_Start", "FY_Offset", "FY_Jahr", "FY_JahrLang", "FY_Quartal", "FY_Monat", "FY_Periode", "FY_JahrMonat", "FY_MonatNr", "FY_QuartalNr"}),

				    Typisiert = Table.TransformColumnTypes(Erweitert, {
				        {"Datum", type date},
				        {"Jahr", Int64.Type},
				        {"Monat Nummer", Int64.Type},
				        {"Tag", Int64.Type},
				        {"Wochentag Nummer", Int64.Type},
				        {"FY_Start", Int64.Type},
				        {"FY_Offset", Int64.Type},
				        {"FY_MonatNr", Int64.Type},
				        {"FY_QuartalNr", Int64.Type}
				    }),

				    Ergebnis = Table.SelectColumns(Typisiert, {
				        "Datum", "Jahr", "Monat Nummer", "Monat", "Tag",
				        "Wochentag", "Wochentag Nummer", "Quartal", "Halbjahr",
				        "FY_Start", "FY_Offset", "FY_Jahr", "FY_JahrLang", "FY_JahrMonat",
				        "FY_Quartal", "FY_QuartalNr", "FY_Monat", "FY_MonatNr", "FY_Periode"
				    })
				in
				    Ergebnis
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
