/// Faktentabelle auf Monatsebene: eine Zeile pro Werk, Monat, Werttyp_Version
/// und Szenario. Die frühere 6-fache Entpivotierung ("Mapping Art"/"Mapping
/// Wert") ist ersetzt: Jede Zeile trägt genau die MetricId, die sich aus dem
/// für ihr Szenario gültigen Cause-of-Change-Stand ergibt (siehe
/// Szenario_Konfig in den Abfragen).
table Revenues
	lineageTag: bda1b3df-fbc6-4a94-9ae1-169be4d301c6

	column Werk
		dataType: int64
		formatString: 0
		lineageTag: c750f3fe-94d2-4036-9dec-ba9ca012b730
		summarizeBy: none
		sourceColumn: Werk

		annotation SummarizationSetBy = Automatic

	column Geschäftsjahr
		dataType: int64
		formatString: 0
		lineageTag: e766aa9c-2b2c-4bf8-89fa-172ceb0233b8
		summarizeBy: none
		sourceColumn: Geschäftsjahr

		annotation SummarizationSetBy = User

	column FY_Offset
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: c1fea6f8-e65d-43f9-81c4-8998ec71a2a7
		summarizeBy: none
		sourceColumn: FY_Offset

		annotation SummarizationSetBy = User

	/// Berichtsjahr (absolutes Geschäftsjahr), auf das sich die Zeile bezieht.
	/// Ein FY26-Jahr kann als Zeile sowohl in Berichtsjahr FY26 (laufend) als
	/// auch FY27 (Vorjahr) erscheinen. Beziehung zu DIM_Berichtsjahr.
	column Berichtsjahr
		dataType: int64
		formatString: 0
		lineageTag: 11fd7c36-e1b7-4510-8404-fd5388aa4ccc
		summarizeBy: none
		sourceColumn: Berichtsjahr

		annotation SummarizationSetBy = User

	column Buchungsperiode
		dataType: int64
		formatString: 0
		lineageTag: 3cfab399-5793-4aa1-a31e-18bedd3d52c1
		summarizeBy: none
		sourceColumn: Buchungsperiode

		annotation SummarizationSetBy = User

	column Werttyp
		dataType: string
		lineageTag: 6e7d9464-a85a-4535-baa6-de8bae6980cd
		summarizeBy: none
		sourceColumn: Werttyp

		annotation SummarizationSetBy = Automatic

	column Version
		dataType: string
		lineageTag: 25720a79-f4a8-4914-9593-f2255b76c8df
		summarizeBy: none
		sourceColumn: Version

		annotation SummarizationSetBy = Automatic

	column Werttyp_Version
		dataType: string
		lineageTag: 27ad9c57-f0aa-4fd4-b202-75e794a71abe
		summarizeBy: none
		sourceColumn: Werttyp_Version

		annotation SummarizationSetBy = Automatic

	column Datum
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8d9b0e26-f6ea-4559-b650-5e8362396605
		summarizeBy: none
		sourceColumn: Datum

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Szenario
		dataType: string
		lineageTag: 5d29a59c-d590-4c94-ac47-062a1fc486be
		summarizeBy: none
		sourceColumn: Szenario

		annotation SummarizationSetBy = Automatic

	/// Aktueller Cause of Change (für abgeschlossene Perioden: der zum
	/// Monatsabschluss eingefrorene Stand).
	column cause_of_change
		dataType: int64
		formatString: 0
		lineageTag: 64d91459-fd0b-4009-b0e3-63b5e65d8553
		summarizeBy: none
		sourceColumn: cause_of_change

		annotation SummarizationSetBy = User

	/// Für das Szenario der Zeile gültiger Cause of Change (Grundlage der
	/// MetricId-Zuordnung).
	column cause_of_change_szenario
		dataType: int64
		formatString: 0
		lineageTag: c534d216-af5a-4ddc-8c98-d3f851137d45
		summarizeBy: none
		sourceColumn: cause_of_change_szenario

		annotation SummarizationSetBy = User

	column MetricId
		dataType: int64
		formatString: 0
		lineageTag: 06289a06-ce08-4ea7-9f0d-f941ff4f22dc
		summarizeBy: none
		sourceColumn: MetricId

		annotation SummarizationSetBy = Automatic

	column Betrag
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: 8469e34c-c8bd-4bad-90ac-1792b921766a
		summarizeBy: sum
		sourceColumn: Betrag

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"de-DE"}

	column IstManuell
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		isHidden
		lineageTag: 34f9e440-4697-4b5c-90c1-a8e4148aa943
		summarizeBy: none
		sourceColumn: IstManuell

		annotation SummarizationSetBy = User

	partition Revenues = m
		mode: import
		source = ```
				let
				    // =========================================================
				    // 1) Quellen: SAP-Export (Lakehouse, MONATLICH) + manuelle Adjustments
				    // =========================================================
				    SapQuelle = Table.AddColumn(SAP_Revenues, "IstManuell", each false, type logical),
				    ManQuelle = Table.AddColumn(Man_Rev, "IstManuell", each true, type logical),
				    Kombiniert = Table.Combine({SapQuelle, ManQuelle}),

				    // CoC-Angaben der manuellen Zeilen eindeutig benennen
				    ManCoC = Table.RenameColumns(Kombiniert, {
				        {"cause_of_change", "Man_cause_of_change"},
				        {"cause_of_change_fy", "Man_cause_of_change_fy"},
				        {"cause_of_change_BUD", "Man_cause_of_change_BUD"},
				        {"cause_of_change_RGF", "Man_cause_of_change_RGF"},
				        {"cause_of_change_R03", "Man_cause_of_change_R03"}}, MissingField.Ignore),
				    OhneNY = Table.RemoveColumns(ManCoC, {"cause_of_change_ny"}, MissingField.Ignore),

				    MitWV = Table.AddColumn(OhneNY, "Werttyp_Version", each [Werttyp] & "_" & [Version], type text),
				    MitOffset = Table.AddColumn(MitWV, "FY_Offset", each [Geschäftsjahr] - Aktuelles_Geschäftsjahr, Int64.Type),

				    // =========================================================
				    // 2) Auf Monatswerte bringen.
				    //    SAP (Lakehouse) ist bereits MONATLICH -> wird nur
				    //    durchgereicht. Manuelle Adjustments (Man_Rev, Excel)
				    //    gelten weiterhin als YTD-kumuliert und werden hier
				    //    differenziert.
				    //    >>> Sind die manuellen Werte MONATLICH erfasst, die
				    //        Bedingung "if IstMan then <diff> else <wert>" auf
				    //        immer <wert> setzen (also nie differenzieren). <<<
				    // =========================================================
				    Gruppiert = Table.Group(MitOffset,
				        {"Werk", "Geschäftsjahr", "FY_Offset", "Werttyp", "Version", "Werttyp_Version", "IstManuell", "Man_cause_of_change", "Man_cause_of_change_fy", "Man_cause_of_change_BUD", "Man_cause_of_change_RGF", "Man_cause_of_change_R03"},
				        {{"Daten", each
				            let
				                IstMan = List.First(_[IstManuell]),
				                ProPeriode = Table.Group(_, {"Buchungsperiode"}, {{"Wert", each List.Sum(List.RemoveNulls([Betrag])) ?? 0, type number}}),
				                Sortiert = Table.Sort(ProPeriode, {{"Buchungsperiode", Order.Ascending}}),
				                Zeilen = Table.ToRecords(Sortiert),
				                Monatlich = List.Transform(List.Positions(Zeilen), (i) =>
				                    [Buchungsperiode = Zeilen{i}[Buchungsperiode],
				                     Betrag = if IstMan
				                              then Zeilen{i}[Wert] - (if i = 0 then 0 else Zeilen{i - 1}[Wert])
				                              else Zeilen{i}[Wert]])
				            in
				                Table.FromRecords(Monatlich, type table [Buchungsperiode = Int64.Type, Betrag = number]),
				          type table [Buchungsperiode = Int64.Type, Betrag = number]}}),
				    MonatlicheWerte = Table.ExpandTableColumn(Gruppiert, "Daten", {"Buchungsperiode", "Betrag"}),

				    // =========================================================
				    // 3) (Vorzeichen wird berichtsjahr-relativ erst in der
				    //    Szenario-Expansion gesetzt, siehe Schritt 5 "MitVZ".
				    //    Hier keine globale Invertierung, da dieselbe Quellzeile
				    //    je nach Berichtsjahr laufend (+) oder Vorjahr (−) ist.)
				    // =========================================================
				    MitVorzeichen = MonatlicheWerte,

				    MitDatum = Table.AddColumn(MitVorzeichen, "Datum", each fnFiscal_PeriodeZuDatum([Geschäftsjahr], [Buchungsperiode]), type date),

				    // =========================================================
				    // 4) Cause of Change:
				    //    - abgeschlossene Perioden: eingefrorener Monats-Stand
				    //    - offene Perioden: aktueller Stammdaten-Stand
				    // =========================================================
				    Historie = Table.Buffer(Stammdaten_Historie),
				    CoCAlle = Table.Buffer(Stammdaten_CoC),

				    JoinFreeze = Table.NestedJoin(MitDatum, {"Werk", "Buchungsperiode"}, Historie, {"betrieb", "Periode"}, "F", JoinKind.LeftOuter),
				    MitFreeze = Table.ExpandTableColumn(JoinFreeze, "F", {"coc_freeze"}),
				    CoCLive = Table.SelectRows(CoCAlle, each [Szenario] = "ACT"),
				    JoinLive = Table.NestedJoin(MitFreeze, {"Werk"}, CoCLive, {"betrieb"}, "L", JoinKind.LeftOuter),
				    MitLive = Table.ExpandTableColumn(JoinLive, "L", {"coc"}, {"coc_live"}),
				    MitCoC = Table.AddColumn(MitLive, "cause_of_change", each
				        if [IstManuell] then [Man_cause_of_change]
				        else if [Buchungsperiode] <= Abgeschlossene_Periode then [coc_freeze]
				        else [coc_live], Int64.Type),

				    // =========================================================
				    // 5) Szenario-Expansion gemäß Szenario_Konfig (berichtsjahr-fähig):
				    //    Je Konfig-Zeile ist das absolute Quelljahr =
				    //    Berichtsjahr_Start + FY_Offset. Faktenzeilen werden darauf
				    //    (und auf Werttyp_Version) gematcht; die MetricId ergibt sich
				    //    aus dem RELATIVEN Offset zum Berichtsjahr. Dadurch kann ein
				    //    FY26-Jahr gleichzeitig als "laufend" (FY26) und als
				    //    "Vorjahr" (FY27) auftreten.
				    // =========================================================
				    Basis = Table.Buffer(MitCoC),
				    Szenarien = List.Distinct(Szenario_Konfig[Szenario]),
				    ProSzenario = List.Transform(Szenarien, (s) =>
				        let
				            Konfig = Table.SelectRows(Szenario_Konfig, each [Szenario] = s),
				            K0 = Konfig{0},
				            BJ = K0[Berichtsjahr_Start],
				            // Konfig-Zeilen -> absolutes Quelljahr (GJ_match) + rel. Offset
				            KonfigGJ = Table.AddColumn(Konfig, "GJ_match", each [Berichtsjahr_Start] + [FY_Offset], Int64.Type),
				            KonfigSel = Table.RenameColumns(Table.SelectColumns(KonfigGJ, {"GJ_match", "Werttyp_Version", "FY_Offset"}), {{"FY_Offset", "rel_offset"}}),
				            JoinK = Table.NestedJoin(Basis, {"Geschäftsjahr", "Werttyp_Version"}, KonfigSel, {"GJ_match", "Werttyp_Version"}, "K", JoinKind.Inner),
				            Zeilen = Table.ExpandTableColumn(JoinK, "K", {"rel_offset"}),
				            // Vorzeichen BERICHTSJAHR-RELATIV: das Vorjahr (rel_offset < 0)
				            // wird negiert, das laufende Jahr bleibt positiv. Das Lakehouse
				            // liefert alles positiv; die Net-New-Measures erwarten das Vorjahr
				            // negativ, damit laufendes + Vorjahr = Wachstum ergibt. Dieselbe
				            // Quellzeile ist so in FY26 "laufend" (+) und in FY27 "Vorjahr" (−).
				            MitVZ = Table.RenameColumns(Table.RemoveColumns(Table.AddColumn(Zeilen, "_Betrag_vz", each if [rel_offset] < 0 then -[Betrag] else [Betrag], type number), {"Betrag"}), {{"_Betrag_vz", "Betrag"}}),
				            CoCTab = Table.SelectRows(CoCAlle, each [Szenario] = s),
				            JoinOffen = Table.NestedJoin(MitVZ, {"Werk"}, CoCTab, {"betrieb"}, "O", JoinKind.LeftOuter),
				            MitOffen = Table.ExpandTableColumn(JoinOffen, "O", {"coc"}, {"coc_offen"}),
				            MitSzCoC = Table.AddColumn(MitOffen, "cause_of_change_szenario", each
				                if [IstManuell] then Record.Field(_, "Man_" & K0[CoC_Spalte_Adjustments])
				                else if K0[Perioden_Freeze] and [Buchungsperiode] <= Abgeschlossene_Periode then [coc_freeze]
				                else [coc_offen], Int64.Type),
				            MitSzenario = Table.AddColumn(MitSzCoC, "Szenario", each s, type text),
				            MitBJ = Table.AddColumn(MitSzenario, "Berichtsjahr", each BJ, Int64.Type),
				            MitMetric = Table.AddColumn(MitBJ, "MetricId", each fnCoC_ZuMetricId([rel_offset], [cause_of_change_szenario]), Int64.Type)
				        in
				            MitMetric),
				    Expandiert = Table.Combine(ProSzenario),

				    // =========================================================
				    // 6) Aufräumen
				    // =========================================================
				    OhneNullzeilen = Table.SelectRows(Expandiert, each [Betrag] <> null and [Betrag] <> 0),
				    Auswahl = Table.SelectColumns(OhneNullzeilen, {"Werk", "Geschäftsjahr", "FY_Offset", "Berichtsjahr", "Buchungsperiode", "Datum", "Werttyp", "Version", "Werttyp_Version", "Szenario", "cause_of_change", "cause_of_change_szenario", "MetricId", "Betrag", "IstManuell"}),
				    Typisiert = Table.TransformColumnTypes(Auswahl, {{"Betrag", Currency.Type}, {"Werk", Int64.Type}, {"Geschäftsjahr", Int64.Type}, {"Buchungsperiode", Int64.Type}, {"Berichtsjahr", Int64.Type}})
				in
				    Typisiert
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
