table Zeitfilter
	lineageTag: 3e13c632-792c-4e60-a004-7fbfd7d4e0d8

	column Ansicht
		dataType: string
		lineageTag: f57fb252-4dd6-4a13-9519-728a97b1150f
		summarizeBy: none
		sourceColumn: Ansicht

		annotation SummarizationSetBy = Automatic

	column Sortierung
		dataType: int64
		formatString: 0
		lineageTag: 99f04075-270f-44ed-86bc-0976d3a84d91
		summarizeBy: sum
		sourceColumn: Sortierung

		annotation SummarizationSetBy = Automatic

	partition Zeitfilter = m
		mode: import
		source =
				let
				    Quelle = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8g1xUdJRMlSK1YlWigSzjZRiYwE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Ansicht = _t, Sortierung = _t]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(Quelle,{{"Ansicht", type text}, {"Sortierung", Int64.Type}})
				in
				    #"Geänderter Typ"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

