/// Berichtskommentare je Werk und Periode, gelesen aus der Fabric-SQL-Datenbank.
/// DirectQuery, damit ein über den Translytical Task Flow gespeicherter Kommentar ohne Modell-Refresh sichtbar ist.
/// Einrichtung von Datenbank, Tabelle und User Data Function: docs/kommentare/README.md.
table Kommentare
	lineageTag: db65c5d3-4f62-5ae6-af2f-a578acb219d0

	/// Technischer Primärschlüssel aus der SQL-Tabelle.
	column Kommentar_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e5242331-cb84-59c8-9e63-b14a26c12263
		summarizeBy: none
		sourceColumn: Kommentar_ID

		annotation SummarizationSetBy = Automatic

	/// Schlüssel Werk * 1.000.000 + Geschäftsjahr * 100 + Periode (in SQL berechnet). Verknüpfung zu Dim_UnitStatus.
	column Status_Key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1aa5ab1e-1ee7-5876-ac92-d1945198668c
		summarizeBy: none
		sourceColumn: Status_Key

		annotation SummarizationSetBy = Automatic

	/// Werksnummer, auf die sich der Kommentar bezieht.
	column Werk
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 292bc4ec-23f5-5ae6-b116-4dd559b950f2
		summarizeBy: none
		sourceColumn: Werk

		annotation SummarizationSetBy = Automatic

	/// SAP-Periode des Kommentars (1 = Oktober).
	column Periode
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 72132ebe-12a6-5c5b-bfa0-81bbc43aa18c
		summarizeBy: none
		sourceColumn: Periode

		annotation SummarizationSetBy = Automatic

	/// Freitext des Kommentars.
	column Kommentar
		dataType: string
		lineageTag: 942f61ec-ce1c-5f7a-9e0d-e8a8dca7637c
		summarizeBy: none
		sourceColumn: Kommentar

		annotation SummarizationSetBy = Automatic

	/// Einordnung des Kommentars (Abrechnung, CoS, Overhead, Umsatz, Sonstiges).
	column Kategorie
		dataType: string
		lineageTag: 5ff9244e-086b-5636-9a14-02574d1cacd4
		summarizeBy: none
		sourceColumn: Kategorie

		annotation SummarizationSetBy = Automatic

	/// Benutzer, der den Kommentar erfasst hat. Wird von der User Data Function aus dem Aufrufkontext gesetzt.
	column Erfasst_von
		dataType: string
		lineageTag: 74ddea66-735c-53b1-9d4a-62ee7a9a201b
		summarizeBy: none
		sourceColumn: Erfasst_von

		annotation SummarizationSetBy = Automatic

	/// Zeitpunkt der Erfassung (UTC).
	column Erfasst_am
		dataType: dateTime
		formatString: dd.mm.yyyy hh:nn
		lineageTag: 1579331f-0569-5d75-ba8a-d214ca4bde1e
		summarizeBy: none
		sourceColumn: Erfasst_am

		annotation SummarizationSetBy = Automatic

	partition Kommentare = m
		mode: directQuery
		queryGroup: Fakten
		source = ```
				let
				    Quelle = Sql.Database(Kommentar_SQL_Endpoint, Kommentar_Datenbank),
				    Tabelle = Quelle{[Schema = "dbo", Item = "Flash_Kommentare"]}[Data],

				    // Zurückgenommene Kommentare bleiben zur Nachvollziehbarkeit in der Tabelle, werden aber ausgeblendet
				    Aktiv = Table.SelectRows(Tabelle, each [Ist_Aktiv] = true),
				    Ergebnis = Table.SelectColumns(Aktiv, {"Kommentar_ID", "Status_Key", "Werk", "Periode", "Kommentar", "Kategorie", "Erfasst_von", "Erfasst_am"})
				in
				    Ergebnis
				```

	annotation PBI_ResultType = Table
