/// Brueckentabelle Person <-> Betrieb (frueher "Betriebeliste").
///
/// Die Zuordnung ist echtes M:N - eine Person verantwortet mehrere Betriebe, und ein Betrieb
/// kann durch unterjaehrige Verantwortungswechsel mehrere Personen haben. Deshalb ist das hier
/// eine reine Bruecke: dim_Person (1) --> brg_Person_Betrieb (n) <-- (1) dim_Betrieb.
/// Nur die Beziehung zu dim_Betrieb ist bidirektional - das ist das Standardmuster fuer
/// Brueckentabellen und die einzige bidirektionale Beziehung im gesamten Modell.
///
/// ACHTUNG Doppelzaehlung: Da in der Quelle keine Gueltigkeitszeitraeume stehen, wird ein
/// Betrieb mit mehreren Verantwortlichen jeder Person in voller Hoehe zugerechnet. Die Summe
/// ueber alle Personen ist dann groesser als der Gesamtwert. Die Measure
/// [Betriebe mit mehreren Verantwortlichen] macht die betroffenen Faelle sichtbar.
table brg_Person_Betrieb
	lineageTag: 514753ff-eb82-45f0-a70f-4e3381824398

	column Vorname
		dataType: string
		lineageTag: 6b806545-2a9d-48e6-bdee-032688bc0d98
		summarizeBy: none
		sourceColumn: Vorname

		annotation SummarizationSetBy = Automatic

	column Nachname
		dataType: string
		lineageTag: e5720da9-4bd7-4367-bcac-7dc7502eef55
		summarizeBy: none
		sourceColumn: Nachname

		annotation SummarizationSetBy = Automatic

	column Funktion
		dataType: string
		lineageTag: ae4bbffc-a1a8-4148-9cd7-42fb3c36dfbe
		summarizeBy: none
		sourceColumn: Funktion

		annotation SummarizationSetBy = Automatic

	column Gebietsleiter
		dataType: string
		lineageTag: c8b0e80a-54ff-4a13-bb29-7c6b9da34380
		summarizeBy: none
		sourceColumn: Gebietsleiter

		annotation SummarizationSetBy = Automatic

	/// Fremdschluessel zu dim_Person[Vollname].
	column Vollname
		dataType: string
		lineageTag: 4143b6eb-06f5-4af4-9097-7b6da4d03da7
		summarizeBy: none
		sourceColumn: Vollname

		annotation SummarizationSetBy = Automatic

	/// Fremdschluessel zu dim_Betrieb[betrieb].
	column Betrieb
		dataType: int64
		formatString: 0
		lineageTag: 44e54fe8-2f1e-4f96-acdb-47474d12c3e4
		summarizeBy: none
		sourceColumn: Betrieb

		annotation SummarizationSetBy = Automatic

	partition brg_Person_Betrieb = m
		mode: import
		source =
				let
				  Quelle = SharePoint.Contents(Sharepoint, [ApiVersion = 15]),
				    #"Shared Documents" = Quelle{[Name="Shared Documents"]}[Content],
				    #"Group Controlling" = #"Shared Documents"{[Name="Group Controlling"]}[Content],
				    #"10_Prämientool" = #"Group Controlling"{[Name="10_Prämientool"]}[Content],
				    #"10_Map 4 Prämientool" = #"10_Prämientool"{[Name="10_Map 4 Prämientool"]}[Content],
				    #"2025_26" = #"10_Map 4 Prämientool"{[Name="2025_26"]}[Content],
				    #"10_Betriebelisten" = #"2025_26"{[Name="10_Betriebelisten"]}[Content],
				    #"Compass Betriebe Liste intern 03 07 2026 xlsx" = #"10_Betriebelisten"{[Name="Compass Betriebe Liste intern 03.07.2026.xlsx"]}[Content],
				    #"Importierte Excel-Arbeitsmappe" = Excel.Workbook(#"Compass Betriebe Liste intern 03 07 2026 xlsx"),
				    Tabelle1_Sheet = #"Importierte Excel-Arbeitsmappe"{[Item="Tabelle1",Kind="Sheet"]}[Data],
				    #"Abgeschnittener Text" = Table.TransformColumns(Table.TransformColumnTypes(Tabelle1_Sheet, {{"Column2", type text}, {"Column7", type text}, {"Column8", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column25", type text}, {"Column26", type text}, {"Column27", type text}, {"Column29", type text}}, "de-DE"),{{"Column1", Text.Trim, type text}, {"Column2", Text.Trim, type text}, {"Column3", Text.Trim, type text}, {"Column4", Text.Trim, type text}, {"Column5", Text.Trim, type text}, {"Column6", Text.Trim, type text}, {"Column7", Text.Trim, type text}, {"Column8", Text.Trim, type text}, {"Column9", Text.Trim, type text}, {"Column10", Text.Trim, type text}, {"Column11", Text.Trim, type text}, {"Column12", Text.Trim, type text}, {"Column13", Text.Trim, type text}, {"Column14", Text.Trim, type text}, {"Column15", Text.Trim, type text}, {"Column16", Text.Trim, type text}, {"Column17", Text.Trim, type text}, {"Column18", Text.Trim, type text}, {"Column19", Text.Trim, type text}, {"Column20", Text.Trim, type text}, {"Column21", Text.Trim, type text}, {"Column22", Text.Trim, type text}, {"Column23", Text.Trim, type text}, {"Column24", Text.Trim, type text}, {"Column25", Text.Trim, type text}, {"Column26", Text.Trim, type text}, {"Column27", Text.Trim, type text}, {"Column28", Text.Trim, type text}, {"Column29", Text.Trim, type text}}),
				    #"Höher gestufte Header" = Table.PromoteHeaders(#"Abgeschnittener Text", [PromoteAllScalars=true]),
				    #"Gefilterte Zeilen" = Table.SelectRows(#"Höher gestufte Header", each ([Betrieb beachten für NAD] = "ja" or [Betrieb beachten für NAD] = "Ja")),
				    #"Andere entfernte Spalten" = Table.SelectColumns(#"Gefilterte Zeilen",{"Betrieb", "Vorname", "Nachname", "Funktion", "Gebietsleiter"}),
				    #"Ersetzte Fehler" = Table.ReplaceErrorValues(#"Andere entfernte Spalten", {{"Vorname", "N.A."}, {"Nachname", "N.A."}, {"Funktion", "N.A."}}),
				    #"Geänderter Typ1" = Table.TransformColumnTypes(#"Ersetzte Fehler",{{"Vorname", type text}, {"Nachname", type text}}),
				    #"Zusammengeführte Spalte eingefügt" = Table.AddColumn(#"Geänderter Typ1", "Vollname", each Text.Combine({[Vorname], " ", [Nachname]}), type text),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Zusammengeführte Spalte eingefügt",{{"Betrieb", Int64.Type}}),
				    #"Ersetzte Fehler1" = Table.ReplaceErrorValues(#"Geänderter Typ", {{"Gebietsleiter", "N.A."}}),
				    // Zeilen ohne Betrieb oder ohne Person koennen in der Bruecke nichts verbinden.
				    #"Gueltige Zuordnungen" = Table.SelectRows(#"Ersetzte Fehler1", each [Betrieb] <> null and [Vollname] <> null and Text.Trim([Vollname]) <> ""),
				    // Grain der Bruecke: eine Zeile je Kombination Person x Betrieb.
				    #"Eindeutige Zuordnungen" = Table.Distinct(#"Gueltige Zuordnungen", {"Vollname", "Betrieb"})
				in
				    #"Eindeutige Zuordnungen"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

