/// Personendimension. Eine Zeile je Person, gespeist aus der Betriebeliste (Verantwortliche)
/// und aus den Personaldaten (Praemienberechtigte), damit beide Seiten denselben Schluessel nutzen.
/// Filtert ueber brg_Person_Betrieb auf die Betriebe und darueber auf die Fakten.
table dim_Person
	lineageTag: 8b1c4f2a-0500-4a10-9d31-1f5a2c7e0500

	/// Primaerschluessel (Vorname + Nachname).
	column Vollname
		dataType: string
		isKey
		lineageTag: 8b1c4f2a-0501-4a10-9d31-1f5a2c7e0501
		summarizeBy: none
		sourceColumn: Vollname

		annotation SummarizationSetBy = Automatic

	column Vorname
		dataType: string
		lineageTag: 8b1c4f2a-0502-4a10-9d31-1f5a2c7e0502
		summarizeBy: none
		sourceColumn: Vorname

		annotation SummarizationSetBy = Automatic

	column Nachname
		dataType: string
		lineageTag: 8b1c4f2a-0503-4a10-9d31-1f5a2c7e0503
		summarizeBy: none
		sourceColumn: Nachname

		annotation SummarizationSetBy = Automatic

	column Funktion
		dataType: string
		lineageTag: 8b1c4f2a-0504-4a10-9d31-1f5a2c7e0504
		summarizeBy: none
		sourceColumn: Funktion

		annotation SummarizationSetBy = Automatic

	column Gebietsleiter
		dataType: string
		lineageTag: 8b1c4f2a-0505-4a10-9d31-1f5a2c7e0505
		summarizeBy: none
		sourceColumn: Gebietsleiter

		annotation SummarizationSetBy = Automatic

	/// Woher die Person stammt: Betriebeliste, Personaldaten oder beides.
	/// Hilfreich zum Aufspueren von Namensabweichungen zwischen den beiden Quellen.
	column Quelle
		dataType: string
		lineageTag: 8b1c4f2a-0506-4a10-9d31-1f5a2c7e0506
		summarizeBy: none
		sourceColumn: Quelle

		annotation SummarizationSetBy = Automatic

	partition dim_Person = m
		mode: import
		source =
				let
				  AusBetriebeliste = Table.AddColumn(
				    Table.SelectColumns(brg_Person_Betrieb, {"Vollname", "Vorname", "Nachname", "Funktion", "Gebietsleiter"}),
				    "Quelle", each "Betriebeliste", type text),
				    AusPersonaldaten = Table.AddColumn(
				      Table.AddColumn(
				        Table.AddColumn(
				          Table.SelectColumns(Personaldaten, {"Vollname", "Vorname", "Nachname"}),
				          "Funktion", each "N.A.", type text),
				        "Gebietsleiter", each "N.A.", type text),
				      "Quelle", each "Personaldaten", type text),
				    Zusammen = Table.Combine({AusBetriebeliste, AusPersonaldaten}),
				    #"Ohne leere Namen" = Table.SelectRows(Zusammen, each [Vollname] <> null and Text.Trim(Text.From([Vollname])) <> ""),
				    // Personen, die in beiden Quellen vorkommen, als "Beides" kennzeichnen.
				    Gruppiert = Table.Group(#"Ohne leere Namen", {"Vollname"}, {
				      {"Vorname", each List.First([Vorname]), type text},
				      {"Nachname", each List.First([Nachname]), type text},
				      {"Funktion", each List.First(List.Select([Funktion], each _ <> "N.A."), "N.A."), type text},
				      {"Gebietsleiter", each List.First(List.Select([Gebietsleiter], each _ <> "N.A."), "N.A."), type text},
				      {"Quelle", each if List.ContainsAll(List.Distinct([Quelle]), {"Betriebeliste", "Personaldaten"}) then "Beides" else List.First([Quelle]), type text}
				    }),
				    #"Sortierte Zeilen" = Table.Sort(Gruppiert, {{"Vollname", Order.Ascending}})
				in
				    #"Sortierte Zeilen"

	annotation PBI_ResultType = Table
