/// MANUELL GEPFLEGTE AUSNAHMELISTE: Betriebe, die ueber einen ANDEREN Betrieb abgerechnet werden.
///
/// Hintergrund: Manche Personen verantworten mehrere Betriebe, werden aber nur ueber einen
/// davon abgerechnet. Diese Zuordnung laesst sich nicht aus den Stammdaten ableiten.
///
/// PFLEGE (Power BI Desktop -> Daten transformieren -> tab_Betriebeset -> Erweiterter Editor):
///   Nur AUSNAHMEN eintragen. Jeder Betrieb, der hier nicht steht, rechnet sich selbst ab.
///   Betrieb            = der Betrieb, dessen Werte mitgerechnet werden sollen
///   Abrechnungsbetrieb = der Betrieb, auf dem die Praemie abgerechnet wird
///
/// BELIEBIG GROSSE SETS: eine Zeile je zugeschlagenem Betrieb. Fuer einen Betriebsleiter mit
/// 5 Betrieben, der ueber 1200 abrechnet, sind es 4 Zeilen - 1200 selbst braucht keine:
///   {1201, 1200, "..."}  {1202, 1200, "..."}  {1203, 1200, "..."}  {1204, 1200, "..."}
///
/// ZWEI FALLSTRICKE:
///   1. KEINE KETTEN bilden. Wer 1201 -> 1200 und gleichzeitig 1200 -> 1100 eintraegt,
///      zerreisst das Set: 1201 landet bei 1200, 1200 aber bei 1100. Immer alle Betriebe
///      eines Sets direkt auf denselben Abrechnungsbetrieb zeigen lassen.
///      Kontrolle: [Kontrolle Betriebeset Ketten] muss 0 sein.
///   2. VERTRAGSART EINHEITLICH halten. Mischt ein Set Pacht- und Mandats-Betriebe, zaehlen
///      [Praemienpunkte max] und [Praemienpunkte erreicht] die Punkte BEIDER Vertragsarten.
///      Kontrolle: [Kontrolle Abrechnungseinheiten gemischte Vertragsart] muss 0 sein.
///
/// Die Zuordnung landet ueber einen Merge als Spalte dim_Betrieb[Abrechnungsbetrieb] und
/// erzeugt daraus die Dimension dim_Abrechnungseinheit. Sobald diese in einem Visual auf den
/// Zeilen liegt, aggregieren Umsatz, UP und Compliance automatisch ueber das ganze Set -
/// es braucht dafuer keine Sonder-Measure.
table tab_Betriebeset
	lineageTag: 8b1c4f2a-0900-4a10-9d31-1f5a2c7e0900

	/// Betrieb, der einem anderen Abrechnungsbetrieb zugeschlagen wird.
	column Betrieb
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 8b1c4f2a-0901-4a10-9d31-1f5a2c7e0901
		summarizeBy: none
		sourceColumn: Betrieb

		annotation SummarizationSetBy = Automatic

	/// Betrieb, auf dem abgerechnet wird. Darf auf sich selbst zeigen.
	column Abrechnungsbetrieb
		dataType: int64
		formatString: 0
		lineageTag: 8b1c4f2a-0902-4a10-9d31-1f5a2c7e0902
		summarizeBy: none
		sourceColumn: Abrechnungsbetrieb

		annotation SummarizationSetBy = Automatic

	/// Freitext zur Nachvollziehbarkeit, wer die Zuordnung wann warum gesetzt hat.
	column Kommentar
		dataType: string
		lineageTag: 8b1c4f2a-0903-4a10-9d31-1f5a2c7e0903
		summarizeBy: none
		sourceColumn: Kommentar

		annotation SummarizationSetBy = Automatic

	partition tab_Betriebeset = m
		mode: import
		source =
				let
				  // ############################################################
				  // ##  HIER PFLEGEN - eine Zeile je Ausnahme                 ##
				  // ##  {Betrieb, Abrechnungsbetrieb, "Kommentar"}            ##
				  // ############################################################
				  Zuordnungen = #table(
				    type table [Betrieb = Int64.Type, Abrechnungsbetrieb = Int64.Type, Kommentar = text],
				    {
				      // Beispiel fuer ein Set aus 5 Betrieben (Abrechnung ueber 1200):
				      // {1201, 1200, "Verantwortung Mustermann, Abrechnung ueber 1200"},
				      // {1202, 1200, "Verantwortung Mustermann, Abrechnung ueber 1200"},
				      // {1203, 1200, "Verantwortung Mustermann, Abrechnung ueber 1200"},
				      // {1204, 1200, "Verantwortung Mustermann, Abrechnung ueber 1200"}
				    }
				  ),
				  // ############################################################
				  // ##  AB HIER NICHTS AENDERN                                ##
				  // ############################################################
				    // Selbstbezuege sind unnoetig und wuerden nur Pflegeaufwand erzeugen.
				    #"Ohne Selbstbezug" = Table.SelectRows(Zuordnungen, each [Betrieb] <> [Abrechnungsbetrieb]),
				    // Ein Betrieb darf nur einem Abrechnungsbetrieb zugeordnet sein.
				    #"Eindeutige Zuordnung" = Table.Distinct(#"Ohne Selbstbezug", {"Betrieb"})
				in
				    #"Eindeutige Zuordnung"

	annotation PBI_ResultType = Table
